---
- name: Downloading Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress.dev/wordpress-{{ wp_version }}.tar.gz

- name: Extracting WordPress
  unarchive: src=/var/www/wordpress.dev/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress.dev/ copy=no
  #command: chdir=/var/www/wordpress.dev/ /bin/tar xfz --owner vagrant --group vagrant --no-same-owner wordpress-{{ wp_version }}.tar.gz creates=/var/www/wordpress.dev/wordpress

- name: Move WordPress files to root directory
  shell: mv /var/www/wordpress.dev/wordpress/* /var/www/wordpress.dev/

- name: Remove wordpress directory
  command: rmdir /var/www/wordpress.dev/wordpress/

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Copy Wordpress config file
  template: src=wp-config.php.j2 dest=/var/www/wordpress.dev/wp-config.php