- name: Install PHP and Dependencies
  apt: pkg={{ item }} state=present
  with_items:
   - php5-fpm
   - php5-cli
   - php5-common
   - php5-curl
   - php5-gd
   - php5-geoip
   - php5-gmp
   - php5-imagick
   - php5-intl
   - php5-json
   - php5-mcrypt
   - php5-memcache
   - php5-memcached
   - php5-mysql
   - php5-xdebug
   - php-apc
   - php-pear

- name: Copy pool configuration file
  template: src=www.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf
  notify: restart php-fpm

- name: Start php-fpm
  service: name=php5-fpm state=started enabled=true